/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	"/health/live": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Live */
		get: operations["live_health_live_get"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/health/ready": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Ready */
		get: operations["ready_health_ready_get"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/v1/analyses": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Create Analysis */
		post: operations["create_analysis_v1_analyses_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		/** AnalysisAcceptedResponse */
		AnalysisAcceptedResponse: {
			/**
			 * Acceptedat
			 * Format: date-time
			 */
			acceptedAt: string;
			/** Analysisrunid */
			analysisRunId: string;
			/** Requestid */
			requestId: string;
			/**
			 * Status
			 * @constant
			 */
			status: "queued";
		};
		/** AnalysisErrorResponse */
		AnalysisErrorResponse: {
			/** Caseid */
			caseId?: string | null;
			/**
			 * Code
			 * @enum {string}
			 */
			code:
				| "INVALID_SERVICE_CREDENTIALS"
				| "INVALID_REQUEST_RELATION"
				| "DUPLICATE_OR_STALE_RUN"
				| "QUEUE_UNAVAILABLE"
				| "STORAGE_UNAVAILABLE"
				| "ARTIFACT_INTEGRITY_MISMATCH"
				| "PARSER_NOT_AVAILABLE";
			/** Message */
			message: string;
			/** Requestid */
			requestId: string;
		};
		/**
		 * AnalysisIntakeRequest
		 * @description Authenticated web-to-analyzer intake contract.
		 *
		 *     The artifact reference is never accepted from a browser.  The service token
		 *     and the relation check in PostgreSQL are what make this reference trusted.
		 */
		AnalysisIntakeRequest: {
			/** Analysisrunid */
			analysisRunId: string;
			artifact: components["schemas"]["ArtifactReference"];
			/** Caseid */
			caseId: string;
			/** Organizationid */
			organizationId: string;
			/** Requestid */
			requestId: string;
			/**
			 * Requestedat
			 * Format: date-time
			 */
			requestedAt: string;
		};
		/** ArtifactReference */
		ArtifactReference: {
			/** Bytesize */
			byteSize: number;
			/** Objectkey */
			objectKey: string;
			/** Sha256 */
			sha256: string;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	live_health_live_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": {
						[key: string]: unknown;
					};
				};
			};
		};
	};
	ready_health_ready_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": {
						[key: string]: unknown;
					};
				};
			};
		};
	};
	create_analysis_v1_analyses_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["AnalysisIntakeRequest"];
			};
		};
		responses: {
			/** @description Successful Response */
			202: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["AnalysisAcceptedResponse"];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["AnalysisErrorResponse"];
				};
			};
			/** @description Not Found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["AnalysisErrorResponse"];
				};
			};
			/** @description Conflict */
			409: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["AnalysisErrorResponse"];
				};
			};
			/** @description Unprocessable Entity */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["AnalysisErrorResponse"];
				};
			};
			/** @description Service Unavailable */
			503: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["AnalysisErrorResponse"];
				};
			};
		};
	};
}
